### ISSUE TITLE
ssm-commons依赖不上

### ISSUE THREAD

**Issue by Michaeljian** [judasn/Basic-Multi-Module-SSM#1]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ssm-manager: Could not resolve dependencies for project com.zhoujian:ssm-manager:pom:1.0-SNAPSHOT: Could not find artifact com.zhoujian:ssm-common:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1

**Comment by Michaeljian** [comment]
这是是什么原因呢，求指教

**Comment by zjs1224522500** [comment]
Could not resolve dependencies for project

**Comment by judasn** [comment]
1.项目里面没有这个包：com.zhoujian:ssm-manager
2.猜测你应该下 clone 后重构了包名。
3.建议重新 clone 一份，然后不要重构的情况下直接运行。
4.如果你要重构，那就需要先了解 IntelliJ IDEA、java、maven 的一些基础点
5.你这个应该看上去应该是重构后没有重新 install

**Comment by Michaeljian** [comment]
谢谢，已经解决了，是没有install
